name: Call action


on:
  pull_request:
    branches:
      - main
      
  workflow_dispatch:
  
jobs:
  call-workflow:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout repository
       uses: actions/checkout@v3
     - name: jirablockerlist action
       uses: SiyaaJhawar/action/Jirablockerlist@main
       with:
        jira_url: 'https://swgup.atlassian.net/rest/api/3/search?filter=allissues'
       
      
       
        
      

    
