name: Call a workflow


on:
  pull_request:
    branches:
      - main
      
  workflow_dispatch:
  
jobs:
  call-workflow:
   runs-on: ubuntu-latest
   steps:

      - name: Call workflow
        uses: SiyaaJhawar/action@main
        with:
          action: SiyaaJhawar/action/.github/workflows/jirablockerlist.yml
       

    
