name: Call Workflow

on:
 push:
    branches:
      - main
 workflow_dispatch:
jobs:
 
  call-workflow:
   uses: SiyaaJhawar/action/.github/workflows/Jirablocker.yml@main
   with:
    token: ${{ secrets.GITHUB_TOKEN }}
