name: Call Workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  call-other-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      -  uses: SiyaaJhawar/action/.github/workflows/Jirablocker.yml@main
