name: Call a workflow


on:
  pull_request:
    branches:
      - main
      
  workflow_dispatch:
  
jobs:
  call-workflow:

     uses: SiyaaJhawar/action/.github/workflows/jirablockerlist.yml@main

    
