name: Callingworkflow
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  Call-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Call workflow
        uses: SiyaaJhawar/action/.github/workflows/CommitComment.yml@main
    
