name: Call Workflow

on:
 push:
    branches:
      - main
 workflow_dispatch:
jobs:
 

  call-other-workflow:
    runs-on: ubuntu-latest
    steps:
     - name: Call other workflow
       uses: SiyaaJhawar/action/.github/workflows/Jirablocker.yml@main
       with:
         token: ${{ secrets.GITHUB_TOKEN }}
