name: My Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
   my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Call reusable workflow from second repository
        uses: https://github.com/SiyaaJhawar/action/blob/main/.github/workflows/main.yml@main
