name: Hello

 

on:
  push:
  push:
    branches: [ main ]
  workflow_dispatch:
  jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: My action
        uses: ./Action
       

        
