name: My Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
    
      
      - uses: SiyaaJhawar/action/.github/workflows/main1.yml@main
 
