name: My Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
    
      - name: Call reusable workflow from another repo
        uses: https://github.com/SiyaaJhawar/action/blob/main/.github/workflows/main.yml@main
 
