name: Hello
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  get-blocker:
    runs-on: ubuntu-latest
    steps:
     
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: My action
        uses: ./action
        
        
