name: Use Private Actions

on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  use-private-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Private Repository
        uses: actions/checkout@v2
      
      - uses: SiyaaJhawar/action/myaction2@main
