name: My Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
       - name: Call reusable workflow from second repository
         uses: SiyaaJhawar/action/.github/workflows/reusable-workflow.yml@main
