name: My Workflow

on:
  push:
    branches:
      - main
workflow_dispatch:

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Call Action 2
        uses: SiyaaJhawar/action1/myaction1@main
