name: Pullrequest

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  myJob:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: My action
        uses: ./PullRequestaddlabel
        env:
   
         MY_TOKEN: ${{ secrets.GITHUB_MY_TOKEN }}
